services:
  scraper-api:
    image: ${DOCKER_USERNAME}/yogi-josim-fastapi-scraper:latest
    container_name: scraper-api
    ports:
      - "8001:8000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    shm_size: '2gb'
    restart: always

networks:
  docker_custom-network:
    external: true