# scraper-api-repo/docker-compose-scraper.yml

services:
  scraper-api:
    image: ${DOCKER_USERNAME}/yogi-josim-fastapi-scraper:latest
    container_name: scraper-api
    ports:
      - "8001:8000"
    shm_size: '2gb'
    restart: always